apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-service
  labels:
    app: kubernetes-api
spec:
  selector:
    app: kubernetes-api
  ports:
    - protocol: TCP
      port: 5173 # Service port
      targetPort: 5173 # Container port
  type: LoadBalancer # NodePort # change to LoadBalancer if running in cloud


#   # service.yaml sets up network routing to pods
# apiVersion: v1
# kind: Service
# metadata:
#   name: kubernetes-api-service
#   labels:
#     app: kubernetes-api
# spec:
#   selector:
#     app: kubernetes-api
#   ports:
#     - protocol: TCP
#       port: 3000 # Service port
#       targetPort: 3000 # Container port
#   type: LoadBalancer # change to LoadBalancer if running in cloud
